# 이 파일은 release note 작성에 사용되는 파일입니다.

changelog:
  name-template: '@Yourssu Design/design-system-react@$RESOLVED_VERSION'
  tag-template: 'v$RESOLVED_VERSION'
  categories:
    - title: ':new: Exciting New Features!'
      label: 'feat'
    - title: ':ladybug: Fixed a Bug'
      labels:
        - 'bug'
        - 'fix'
    - title: ':heart_hands::skin-tone-2: Improve User Experience'
      label: 'docs'
    - title: ':hammer_and_wrench: Strive for Better Code'
      label: 'refactor'
    - title: 'ETC'
      labels:
        - '*'
  change-template: '* $TITLE (#$NUMBER) by @$AUTHOR'
  change-title-escapes: '\<*_&#@`'
  exclude-labels:
    - 'Main'
  version-resolver:
    major:
      labels:
        - 'Major'
    minor:
      labels:
        - 'Minor'
    patch:
      labels:
        - 'Patch'
    default: patch
  template: |
    $CHANGES
