export type Typo =
  | 'display1'
  | 'display2'
  | 'display3'
  | 'title1'
  | 'title2'
  | 'title3'
  | 'title4'
  | 'title5'
  | 'subtitle1'
  | 'subtitle2'
  | 'subtitle3'
  | 'subtitle4'
  | 'subtitle5'
  | 'subtitle6'
  | 'body1'
  | 'body2'
  | 'body3'
  | 'button0'
  | 'button1'
  | 'button2'
  | 'button3'
  | 'button4'
  | 'caption0'
  | 'caption1'
  | 'caption2';

export type FontWeight = 'Regular' | 'Medium' | 'SemiBold' | 'Bold';
